### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by Viq111** [Viq111/tri#1]
_Roadmap is always subject to change but hopefully the vision is already pretty clear_

# Milestones

## Milestone 0.1.1 - local rsync
- [x] Full copy folder A -> folder B
- [ ] Default to ask for deletion for files in B but not in A (can auto-delete with `-allow-delete`)
- [x] Only copy file A -> B on change (!= modtime)
- [x] Only copy file A -> B on file created (not full sync)

----------
## Milestone 0.1.2 - security
- [ ] Can encode/decode using weak(symetric)/strong(asymetric)
- [ ] Can encode/decode filenames
- [ ] Can encode/decode files
- [ ] Allow a compression layer (in this milestone because easy to do once we have the crypt layer)
- [ ] sync A -> (crypt) B, B -> (decrypt) C with A == C works

----------
## Milestone 0.1.3 - security (part 2) + RFCs
- [ ] Fileformat for security key files (weak & strong)
- [ ] Draft of fileformat for file
  - compression (+ tar)
  - security
  - hashs ?
- [ ] ...

----------
## Milestone 0.1.4 - cloud sync - 1 provider (probably b2)
- [ ] Auth layer
- [ ] Persistant config
- [ ] API <-> `storage` integration

----------
## Milestone 0.1.5 - stats
- [ ] Storage benchmarks: nb API/sys calls, API latency, Download/Upload speed
- [ ] Top level stats for nb calls (see dd s3 integration)
- [ ] ...

----------
## Milestone 0.1.6 - Indexing
- [ ] Fileformat for index
- [ ] Security for index (probably weak)
- [ ] Build index
- [ ] Full check index
- [ ] Update index
- [ ] ...

----------
## Milestone 0.2 - GUI
- [ ] Choose UI library (QT vs Electron vs Native)
- [ ] How will UI interact with tool ? (socket, cli, ?)
